// <auto-generated />

#pragma warning disable CS1591
// ReSharper disable RedundantArgumentDefaultValue
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantUsingDirective

using System.Diagnostics.CodeAnalysis;
using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DIGOS.Ambassador.Plugins.Anonymail.Migrations
{
    [ExcludeFromCodeCoverage]
    public partial class InitialCreate : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "AnonymailModule");

            migrationBuilder.EnsureSchema(
                name: "Core");

            migrationBuilder.CreateTable(
                name: "AnonymizedUsers",
                schema: "AnonymailModule",
                columns: table => new
                {
                    ID = table.Column<long>(nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    IdentityHash = table.Column<Guid>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AnonymizedUsers", x => x.ID);
                });

            migrationBuilder.CreateTable(
                name: "AnonymousMailboxes",
                schema: "AnonymailModule",
                columns: table => new
                {
                    ID = table.Column<long>(nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    ServerID = table.Column<long>(nullable: false),
                    DiscordChannelID = table.Column<long>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AnonymousMailboxes", x => x.ID);
                    table.ForeignKey(
                        name: "FK_AnonymousMailboxes_Servers_ServerID",
                        column: x => x.ServerID,
                        principalSchema: "Core",
                        principalTable: "Servers",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "AnonymousMailboxUsers",
                schema: "AnonymailModule",
                columns: table => new
                {
                    ID = table.Column<long>(nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    UserID = table.Column<long>(nullable: false),
                    MailboxID = table.Column<long>(nullable: false),
                    IsBlocked = table.Column<bool>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AnonymousMailboxUsers", x => x.ID);
                    table.ForeignKey(
                        name: "FK_AnonymousMailboxUsers_AnonymousMailboxes_MailboxID",
                        column: x => x.MailboxID,
                        principalSchema: "AnonymailModule",
                        principalTable: "AnonymousMailboxes",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_AnonymousMailboxUsers_AnonymizedUsers_UserID",
                        column: x => x.UserID,
                        principalSchema: "AnonymailModule",
                        principalTable: "AnonymizedUsers",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "AnonymousMails",
                schema: "AnonymailModule",
                columns: table => new
                {
                    ID = table.Column<long>(nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    AuthorID = table.Column<long>(nullable: false),
                    Timestamp = table.Column<DateTimeOffset>(nullable: false),
                    Contents = table.Column<string>(nullable: false),
                    AnonymousMailboxID = table.Column<long>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AnonymousMails", x => x.ID);
                    table.ForeignKey(
                        name: "FK_AnonymousMails_AnonymousMailboxes_AnonymousMailboxID",
                        column: x => x.AnonymousMailboxID,
                        principalSchema: "AnonymailModule",
                        principalTable: "AnonymousMailboxes",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_AnonymousMails_AnonymizedUsers_AuthorID",
                        column: x => x.AuthorID,
                        principalSchema: "AnonymailModule",
                        principalTable: "AnonymizedUsers",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_AnonymizedUsers_IdentityHash",
                schema: "AnonymailModule",
                table: "AnonymizedUsers",
                column: "IdentityHash",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_AnonymousMailboxes_ServerID",
                schema: "AnonymailModule",
                table: "AnonymousMailboxes",
                column: "ServerID");

            migrationBuilder.CreateIndex(
                name: "IX_AnonymousMailboxUsers_MailboxID",
                schema: "AnonymailModule",
                table: "AnonymousMailboxUsers",
                column: "MailboxID");

            migrationBuilder.CreateIndex(
                name: "IX_AnonymousMailboxUsers_UserID",
                schema: "AnonymailModule",
                table: "AnonymousMailboxUsers",
                column: "UserID");

            migrationBuilder.CreateIndex(
                name: "IX_AnonymousMails_AnonymousMailboxID",
                schema: "AnonymailModule",
                table: "AnonymousMails",
                column: "AnonymousMailboxID");

            migrationBuilder.CreateIndex(
                name: "IX_AnonymousMails_AuthorID",
                schema: "AnonymailModule",
                table: "AnonymousMails",
                column: "AuthorID");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "AnonymousMailboxUsers",
                schema: "AnonymailModule");

            migrationBuilder.DropTable(
                name: "AnonymousMails",
                schema: "AnonymailModule");

            migrationBuilder.DropTable(
                name: "AnonymousMailboxes",
                schema: "AnonymailModule");

            migrationBuilder.DropTable(
                name: "AnonymizedUsers",
                schema: "AnonymailModule");
        }
    }
}

